import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  isAuthorized: false,
  isLoading: true,
  user: {
    email: "",
    phone: "",
    fullName: " ",
    role: "",
    avatar: "",
    id: "",
  },
  tempAvatar: "",
};

export const accountSlice = createSlice({
  name: "account",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    doLoginAction: (state, action) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.isAuthorized = true;
      state.isLoading = false;
      state.user = action.payload;
    },
    doGetAccountAction: (state, action) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.isAuthorized = true;
      state.isLoading = false;
      state.user = action.payload.user;
    },
    doLogoutAction: (state, action) => {
      localStorage.removeItem("access_token");
      state.isAuthorized = false;
      state.isLoading = true;
      state.user = {
        email: "",
        phone: "",
        fullName: " ",
        role: "",
        avatar: "",
        id: "",
      };
    },
    doUpdateUserInfo: (state, action) => {
      state.user.avatar = action.payload.avatar;
      state.user.phone = action.payload.phone;
      state.user.fullName = action.payload.fullName;
    },
    doUploadAvatar: (state, action) => {
      console.log(action.payload.avatar);
      state.tempAvatar = action.payload.avatar;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {},
});

export const {
  doLoginAction,
  doGetAccountAction,
  doLogoutAction,
  doUpdateUserInfo,
  doUploadAvatar,
} = accountSlice.actions;

export default accountSlice.reducer;
